apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crane-predictor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crane-predictor
subjects:
  - kind: ServiceAccount
    name: crane-predictor
    namespace: crane-system