run:
  timeout: 30m

linters:
  disable-all: true
  enable:
    - deadcode
    - unused
    - varcheck
    - ineffassign
    - goimports
    - gofmt
    - misspell
    - unparam
    - unconvert
    - govet
    - errcheck
    - structcheck
    - staticcheck

linters-settings:
  staticcheck:
    go: "1.20"
    checks: [
      "all",
      "-SA1019", # TODO(fix) Using a deprecated function, variable, constant or field
    ]
  unused:
    go: "1.20"
