kind: ServiceAccount
apiVersion: v1
metadata:
  name: metric-adapter
  namespace: crane-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metric-adapter
  name: metric-adapter
  namespace: crane-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-adapter
  template:
    metadata:
      labels:
        app: metric-adapter
      name: metric-adapter
    spec:
      serviceAccountName: metric-adapter
      containers:
        - name: metric-adapter
          image: docker.io/gocrane/metric-adapter:v0.3.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
          args:
            - /metric-adapter
            - --secure-port=6443
            - --alsologtostderr=true
          ports:
            - containerPort: 6443
              name: https
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /tmp
              name: temp-vol
      volumes:
        - name: temp-vol
          emptyDir: {}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: metric-router-config
  namespace: crane-system
data:
  router.yaml: |-
    apiVersion: metricrouter.crane.io/v1alpha1
    kind: MetricRouter
    apiservices:
      - service:
          name: hpa-metric-service
          namespace: kube-system
        group: external.metrics.k8s.io
        insecureSkipTLSVerify: true
      - service:
          name: hpa-metric-service1
          namespace: kube-system
        group: custom.metrics.k8s.io
        insecureSkipTLSVerify: true