
apiVersion: v1
kind: Namespace
metadata:
  name: crane-system

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: craned
  namespace: crane-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: craned
  namespace: crane-system
  labels:
    app: craned
spec:
  replicas: 1
  selector:
    matchLabels:
      app: craned
  template:
    metadata:
      labels:
        app: craned
    spec:
      serviceAccountName: craned
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
      containers:
        - name: craned
          image: docker.io/gocrane/craned
          imagePullPolicy: IfNotPresent
          command:
            - /craned
            - -v=4
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-tls
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWakNDQWo2Z0F3SUJBZ0lKQU9vSDdESmN5UkMxTUEwR0NTcUdTSWIzRFFFQkJRVUFNQkF4RGpBTUJnTlYKQkFNTUJXTnlZVzVsTUI0WERUSXhNVEl3T0RFd01qZzFPVm9YRFRJeU1ERXdOekV3TWpnMU9Wb3dLekVwTUNjRwpBMVVFQXd3Z2QyVmlhRzl2YXkxelpYSjJhV05sTG1OeVlXNWxMWE41YzNSbGJTNXpkbU13Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURGNXhHdGhlcGJON0FoNHpvWDNqR3ZRQ3RSWm1RV0RPdXIKUFZpY3NYOENwbEtwaFdSK2NwdmljcEs1UDljWDludnkyQlBzbGVQeHNLa2txU2J3K05GNEFJMDFFMDZkdWpkUQpLVFdHbEZCNGNWaTRkQTIyVVc4VnFxQzhQMFdDYlhMRTJ6amVlQ3NXQ1pTN2dtaUdrMURlbHA0a1hNK0k0NXZiCjA2bFVJUjIvRGpDOHZaMDFEQWlTRkQxLzJQUElueG9TMHZ4MnU4QUdtMk84K3o0K044R2ExalpaK3RrTWsvZnIKelkzUEYrKzg1ZDVESWZLeG8wN3NRVFhyNUZKUWlSNzJhQjk5WnYrVlRSUDlUU2ZNdmNQVVFLZGNvdjF4dHlLbQp6b0hQVGVjVHlhN1lPWW1sNVFqSlUzSHFTYTNGQzZqMk5IKytzWVl0SCtNRkgrTHdOaW41QWdNQkFBR2pnWmN3CmdaUXdDUVlEVlIwVEJBSXdBREFMQmdOVkhROEVCQU1DQmVBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3SUcKQ0NzR0FRVUZCd01CTUZzR0ExVWRFUVJVTUZLQ0lIZGxZbWh2YjJzdGMyVnlkbWxqWlM1amNtRnVaUzF6ZVhOMApaVzB1YzNaamdpNTNaV0pvYjI5ckxYTmxjblpwWTJVdVkzSmhibVV0YzNsemRHVnRMbk4yWXk1amJIVnpkR1Z5CkxteHZZMkZzTUEwR0NTcUdTSWIzRFFFQkJRVUFBNElCQVFDUFJnVDNEdHNCYVRmM255NDl4QXpScjlhQUV1YlgKYklWNjc1OS92djZEcldxRDhUNXRKNkJocGxiSWNHRVJxelJtd1B5anVNamNxekJVSWlGbTlXcTVTRytuN1NRdgpPeXEvTGtpUmVqWWo5YWlHd2JnMVg2S0QveGN0QThHa1dhQXlZRC9NRUhGeVR6TW9NZ0N0UVR4UEx3c3M2OHlSCm5DR3VMejVNQU9FZmdrWEJkUjBkamlPSnFEZVliaS9md0Nwam43R3ZUUUxxaDJzVWxLSkJpRmpzaURLN1YxblIKNlN2QlpIVHBWTHBWK0NYYlA4WVhjV21tcmM3VmcxaldWa3lGM2V6aUVuTktxZnZvcll3aHh6UVZGaXVVS09QRApKTEhoZXYwd3BoNXFSU2s2czBQSURLS1FQcWlYVjROSFJPTGI0ZnVVWHQraG9uZ21YbWRldDJCVQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBeGVjUnJZWHFXemV3SWVNNkY5NHhyMEFyVVdaa0ZnenJxejFZbkxGL0FxWlNxWVZrCmZuS2I0bktTdVQvWEYvWjc4dGdUN0pYajhiQ3BKS2ttOFBqUmVBQ05OUk5PbmJvM1VDazFocFJRZUhGWXVIUU4KdGxGdkZhcWd2RDlGZ20xeXhOczQzbmdyRmdtVXU0Sm9ocE5RM3BhZUpGelBpT09iMjlPcFZDRWR2dzR3dkwyZApOUXdJa2hROWY5anp5SjhhRXRMOGRydkFCcHRqdlBzK1BqZkJtdFkyV2ZyWkRKUDM2ODJOenhmdnZPWGVReUh5CnNhTk83RUUxNitSU1VJa2U5bWdmZldiL2xVMFQvVTBuekwzRDFFQ25YS0w5Y2JjaXBzNkJ6MDNuRThtdTJEbUoKcGVVSXlWTng2a210eFF1bzlqUi92ckdHTFIvakJSL2k4RFlwK1FJREFRQUJBb0lCQUZINm9pd0xhVVZZRURJNQplbnNnbzl4QTdMRFBoVzVNOCtML2lwRitSV3JIa3o1OTcxOGlBc2tQUlJCUURiM3pjT3pyN1hUM3NuRVFDVUVTCmdQc1pWMHdxamxRS0oyclhGTXEwQjJRMFZCRlFncndGOXhncks2VUNCWXQxZWtuSkpOMi9JaE9tRzlNSkxQOXYKeWZUVldZNmJQZTg2TXc0MW12NjQ4MC9TV0F3b0RZcC9CcThMWml2Y2hZcmVqUFRYeTJ4VmpWbGZsWmJhY1JVeApDOHU2WjlBaUw5aTlXWWk2RlJpZ2lyckR3TnVtTDhOc2xOdThBRm5DNjRLWEhPb1pVRG16ZnZIYUFDT1AyTlpDCjNPZ3hzbmJ2S3V6NTJ6VEo1c05XV1FsWFpaQmRQbSt1QjZnanNPZG55bXdHZGRld3A3N21pOUZ2OXlSUGJqUE0KKzRpazFnRUNnWUVBOVBNOUpITEtIeGppSStJaldMa2R0K0hMaS8wdmNwVElRcE5YUGgrdWJPYVZSQ04xRlRiUQpQQTN1eG52V2FiNUJlcWdIOGcxV3IyS0J5QXk0Zlp4UGpoNHBuaGRYSkRhNTJlcXp0TmZJNDlwc3dpbzVDeVh3Clc4enhmZ3VVZ0lGZ1dKVXc4ZUJLMmd4aTdOcFh0U1JsRlN4ZTBZaUJpUGJFbmdNVFlJbnZQRkVDZ1lFQXp0U0MKcjU3bEhJT3hweTZNMVRxdjBEZVZQMS9qNVc0TmNhaW9vVy9XbFlUNUJCQnozVm52cU5TbXUrY2hJRTg0SS84RQpNcnJZNW1WUlkrLzRIMkJrVVVKdEhzbStxcDhjM0Q3RmVhUmRKTEc3SWt6MTlWT0pRdEovWkdkcjNFSUxET09zCjFCQjdJVDQ3K29XQjdYcm9jTGE2S0ZpejJaQ3JiOU9XSnlRNk1Ta0NnWUJYeCt0N2FsK2dzVXdwUzlzYTZvd0oKMzdNUUlkV2xIRWlBQTBsYWpBUDRKdElMTHlIQVRucGxheURNcEloOE1LQktrbmoyZDIwL1FPLzlmd0dHa2tPNApUSHJobXIreHpLTGh3MGhQWUowdmVwRkxLOUp4ZWxFZXROMCtMR3cxZVNmTDF2dEpVdlhBR254QklTWVpWa2ViClJPRmQrYXRpSi96aUczd1FOcDR6WVFLQmdDblBTNXUwd3h2QWcya0lQKy9hclMrcURNR0M0TTdBTUhlSllJMUIKemw3clFtdFA2QndXMGh1TzRTV2EwMWQwckNTYXFINll4ci9NTzJlNFdxLzlERXBnNHk0V0dqVGpkVElRZmxyWQpudnVMOGdnOUJudFJKNjRhWHlZc3dlRUVlTGRpVHMyUGgxUnhBQzdrVGg5emVRbFA1dEhCSEpvZVpJbDJmQ1B0CmJ0WUJBb0dBTUpKbmVaUzhUQ01kbVJnWFlYZ3J6K0JOSFFtSHorUkJxYTZyYjN4YkpiTC9pRllNZDY0VnRtMWoKTHB2YTkxUXcrcldLY01Hb21jYTh0NllaOEVhMmlaZFRHR3JWdU5qSEEzMnVScjdjR0F5VVdUa0dndWdOVHdMYgphYmRNV25jWlBneFQ3NjY1VWx0Zjd2ejlOS3V6aFJnSEw3RUlxWVlqM1RFemVqaVdxTkU9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: webhook-server-tls
  namespace: crane-system
type: kubernetes.io/tls