
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: crane-mutating-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNuRENDQVlRQ0NRRDdJeXZTaDZPRUZEQU5CZ2txaGtpRzl3MEJBUXNGQURBUU1RNHdEQVlEVlFRRERBVmoKY21GdVpUQWVGdzB5TVRFeU1EZ3hNREk0TlRsYUZ3MHlNakF4TURjeE1ESTROVGxhTUJBeERqQU1CZ05WQkFNTQpCV055WVc1bE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNGw0QzEwYjI2a29tCkx0OEg2cWtWYzdBVzRHSmgzWjc3Vno2VU5DVUp4ZlpiR2VHS211dXhkVEdlQXNUbFoySnVOOWR3VkFnajFLUE8KVDFSUFNFd2doQk0yaXNYV1p4Yi84WG9yK0NXbTUvMnNvR1V4SnRsRjFnVjFjTG1QSlVxMGd0VmhQRzdaZVZtVgp2d2c0T3hUdlVEbGY1blFQZjZucW5NeVB2U1diRGZLTjhrQTRscUhZalVRV3VNRXV4U2pya3Zvalc5WGE0WmEyCmZIQTFvOE9VQmthVTVpUVZiTlNTajQyZzh6anFMZ043RERRRkplZnBiU2syKzZ0MkpiTVhnTG1QL3hQMTdrQVoKMFJoQ3I0cmRRcEMyZHpBRkpVZ2toVTA0OC9kL1VzellycVpDRDRmcjlyMnM0S0g1d0Y0dkg0OXdGNGNhVWxKRAozaVFEa25pN0d3SURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFEZEhGZ0E5TGRtNmpLRDN0dTNLOFZsCmFLTzdjb0tadjdaemZ1Rk1SYmM5REM4QmVTZm9ueTNNRnJKVHZiVmFWK2l6UVA3cEt3YmpSY2RveVd5L2JYSWwKUnJqdy9lY2ZPa252SmFtTSs2OCt0cDhXYjR3d1p5eWZGbEVJdWp3bFRmT1MwUHNkcDcycHpmcXppNjZ4TGgzSgppQWtxd3ZSbWc5eEY1dm9EQmlVQUN0UkozTzVNaWNMZWNZekw2c3BuR0N4aHVWSEduamZsb2JjM2hkMHpnK1FvCjFTSW9hUml3eEJ5dThWVkVFZW05WStYWEJadjJBMms5WmtVOFRTdVNReVVzL0c5UW1sVVJxN0dZVTZ2aGRxdFoKQ1pZU3dhOWpsUzU0L25aQXdsa2VkWVJIZFkvLzhIUEJPUXcxbk1tWU9kNXFvaWVJZEZhOFQzUy9WeGJhb0lCcAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: webhook-service
      namespace: crane-system
      path: /mutate-prediction-crane-io-v1alpha1-timeseriesprediction
  failurePolicy: Fail
  name: mprediction.crane.io
  rules:
  - apiGroups:
    - prediction.crane.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - TimeSeriesPrediction
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: crane-validating-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNuRENDQVlRQ0NRRDdJeXZTaDZPRUZEQU5CZ2txaGtpRzl3MEJBUXNGQURBUU1RNHdEQVlEVlFRRERBVmoKY21GdVpUQWVGdzB5TVRFeU1EZ3hNREk0TlRsYUZ3MHlNakF4TURjeE1ESTROVGxhTUJBeERqQU1CZ05WQkFNTQpCV055WVc1bE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNGw0QzEwYjI2a29tCkx0OEg2cWtWYzdBVzRHSmgzWjc3Vno2VU5DVUp4ZlpiR2VHS211dXhkVEdlQXNUbFoySnVOOWR3VkFnajFLUE8KVDFSUFNFd2doQk0yaXNYV1p4Yi84WG9yK0NXbTUvMnNvR1V4SnRsRjFnVjFjTG1QSlVxMGd0VmhQRzdaZVZtVgp2d2c0T3hUdlVEbGY1blFQZjZucW5NeVB2U1diRGZLTjhrQTRscUhZalVRV3VNRXV4U2pya3Zvalc5WGE0WmEyCmZIQTFvOE9VQmthVTVpUVZiTlNTajQyZzh6anFMZ043RERRRkplZnBiU2syKzZ0MkpiTVhnTG1QL3hQMTdrQVoKMFJoQ3I0cmRRcEMyZHpBRkpVZ2toVTA0OC9kL1VzellycVpDRDRmcjlyMnM0S0g1d0Y0dkg0OXdGNGNhVWxKRAozaVFEa25pN0d3SURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFEZEhGZ0E5TGRtNmpLRDN0dTNLOFZsCmFLTzdjb0tadjdaemZ1Rk1SYmM5REM4QmVTZm9ueTNNRnJKVHZiVmFWK2l6UVA3cEt3YmpSY2RveVd5L2JYSWwKUnJqdy9lY2ZPa252SmFtTSs2OCt0cDhXYjR3d1p5eWZGbEVJdWp3bFRmT1MwUHNkcDcycHpmcXppNjZ4TGgzSgppQWtxd3ZSbWc5eEY1dm9EQmlVQUN0UkozTzVNaWNMZWNZekw2c3BuR0N4aHVWSEduamZsb2JjM2hkMHpnK1FvCjFTSW9hUml3eEJ5dThWVkVFZW05WStYWEJadjJBMms5WmtVOFRTdVNReVVzL0c5UW1sVVJxN0dZVTZ2aGRxdFoKQ1pZU3dhOWpsUzU0L25aQXdsa2VkWVJIZFkvLzhIUEJPUXcxbk1tWU9kNXFvaWVJZEZhOFQzUy9WeGJhb0lCcAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: webhook-service
      namespace: crane-system
      path: /validate-prediction-crane-io-v1alpha1-timeseriesprediction
  failurePolicy: Fail
  name: vprediction.crane.io
  rules:
  - apiGroups:
    - prediction.crane.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - timeseriespredictions
  sideEffects: None
