apiVersion: v1
kind: Pod
metadata:
  name: low
  labels:
    k8s-app: low
    preemptible_job: "true"
spec:
  containers:
    - command:
        - stress-nga
        - -c
        - "2"
        - --cpu-method
        - cpuid
      image: ccr.ccs.tencentyun.com/tkeimages/stress-ng:v0.12.09.ln
      imagePullPolicy: IfNotPresent
      name: low
      resources:
        limits:
          gocrane.io/cpu: "2"
          gocrane.io/memory: "2000Mi"
        requests:
          gocrane.io/cpu: "2"
          gocrane.io/memory: "2000Mi"
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30