kind: Service
apiVersion: v1
metadata:
  name: crane-predictor
spec:
  selector:
    k8s-app: crane-predictor
  type: ClusterIP
  ports:
    - name: crane-predictor
      port: 7777
      targetPort: 7777
