apiVersion: ensurance.crane.io/v1alpha1
kind: NodeQOS
metadata:
  name: eviction-on-high-mem-usage
spec:
  nodeQualityProbe:
    nodeLocalGet:
      localCacheTTLSeconds: 60
    timeoutSeconds: 10
  rules:
    - actionName: eviction
      avoidanceThreshold: 2
      metricRule:
        name: memory_total_usage
        value: 5000000000 # means 5Gi
      name: mem-usage
      restoreThreshold: 2
      strategy: None