apiVersion: analysis.crane.io/v1alpha1
kind: Analytics
metadata:
  name: workload-replicas
  namespace: crane-system               # The Analytics in Crane-system will select all resource across all namespaces.
spec:
  type: Replicas                        # This can only be "Resource" or "Replicas".
  completionStrategy:
    completionStrategyType: Periodical  # This can only be "Once" or "Periodical".
    periodSeconds: 86400                # analytics selected resources every 1 day
  resourceSelectors:                    # defines all the resources to be select with
    - kind: Deployment
      apiVersion: apps/v1
    - kind: StatefulSet
      apiVersion: apps/v1
  config: # defines all the configuration for this analytics
    replicas.fluctuation-threshold: "0"
    replicas.min-cpu-usage-threshold: "0"