apiVersion: analysis.crane.io/v1alpha1
kind: Analytics
metadata:
  name: craned-resource
  namespace: crane-system
spec:
  type: Resource                        # This can only be "Resource" or "HPA".
  completionStrategy:
    completionStrategyType: Periodical  # This can only be "Once" or "Periodical".
    periodSeconds: 86400                # analytics selected resources every 1 day
  resourceSelectors:                    # defines all the resources to be select with
    - kind: Deployment
      apiVersion: apps/v1
      name: craned

---

apiVersion: analysis.crane.io/v1alpha1
kind: Analytics
metadata:
  name: metric-adapter-resource
  namespace: crane-system
spec:
  type: Resource                       # This can only be "Resource" or "HPA".
  completionStrategy:
    completionStrategyType: Periodical # This can only be "Once" or "Periodical".
    periodSeconds: 3600                # analytics selected resources every 1 hour
  resourceSelectors:                   # defines all the resources to be select with
    - kind: Deployment
      apiVersion: apps/v1
      name: metric-adapter


