apiVersion: autoscaling.crane.io/v1alpha1
kind: EffectiveHorizontalPodAutoscaler
metadata:
  name: hpa-load
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ahpa-load
  minReplicas: 20
  maxReplicas: 150
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  predictionConfig:
    predictionWindow: 3600
    predictionAlgorithm:
      algorithmType: dsp
      dsp:
        sampleInterval: "60s"
        historyLength: "3d"
