apiVersion: prediction.crane.io/v1alpha1
kind: TimeSeriesPrediction
metadata:
  name: workload-resource-dsp
  namespace: default
spec:
  targetRef:
    kind: Deployment
    name: dep-1-100m-500mib
    namespace: default
  predictionWindowSeconds: 3600
  predictionMetrics:
    - resourceIdentifier: workload-cpu
      type: ResourceQuery
      resourceQuery: cpu
      algorithm:
        algorithmType: "dsp"
        dsp:
          sampleInterval: "60s"
          historyLength: "3d"
          estimators:
            fft:
              - marginFraction: "0.2"
                lowAmplitudeThreshold: "1.0"
                highFrequencyThreshold: "0.05"
                minNumOfSpectrumItems: 10
                maxNumOfSpectrumItems: 20
    - resourceIdentifier: workload-mem
      type: ResourceQuery
      resourceQuery: memory
      algorithm:
        algorithmType: "dsp"
        dsp:
          sampleInterval: "60s"
          historyLength: "3d"
          estimators:
            fft:
              - marginFraction: "0.2"
                lowAmplitudeThreshold: "1.0"
                highFrequencyThreshold: "0.05"
                minNumOfSpectrumItems: 10
                maxNumOfSpectrumItems: 20