apiVersion: prediction.crane.io/v1alpha1
kind: TimeSeriesPrediction
metadata:
  name: workload-resource-dsp
  namespace: default
spec:
  predictionWindowSeconds: 3600
  predictionMetrics:
    - resourceIdentifier: workload-cpu
      workloadRef:
        kind: Deployment
        name: dep-1-100m-500mib
        namespace: default
        resource: cpu
      algorithm:
        algorithmType: "dsp"
        dsp:
          sampleInterval: "60s"
          historyLength: "3d"
          estimators:
            fft:
              - marginFraction: "0.2"
                lowAmplitudeThreshold: "1.0"
                highFrequencyThreshold: "0.05"
                minNumOfSpectrumItems: 10
                maxNumOfSpectrumItems: 20
    - resourceIdentifier: workload-mem
      workloadRef:
        kind: Deployment
        name: dep-1-100m-500mib
        namespace: default
        resource: memory
      algorithm:
        algorithmType: "dsp"
        dsp:
          sampleInterval: "60s"
          historyLength: "3d"
          estimators:
            fft:
              - marginFraction: "0.2"
                lowAmplitudeThreshold: "1.0"
                highFrequencyThreshold: "0.05"
                minNumOfSpectrumItems: 10
                maxNumOfSpectrumItems: 20