name: ci
on:
  push:
  pull_request:
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - run: go install github.com/golang/mock/mockgen@v1.6.0
      - run: cp $(go env GOPATH)/bin/mockgen /usr/local/bin/
      - run: mockgen -version
      - name: Run GoReleaser Snapshot
        uses: goreleaser/goreleaser-action@v3
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser Tag
        uses: goreleaser/goreleaser-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload assets Darwin_arm64
        uses: actions/upload-artifact@v3
        with:
          name: Darwin_arm64
          path: dist/*Darwin_arm64.tar.gz
      - name: Upload assets Darwin_x86_64
        uses: actions/upload-artifact@v3
        with:
          name: Darwin_x86_64
          path: dist/*Darwin_x86_64.tar.gz
      - name: Upload assets Linux_arm64
        uses: actions/upload-artifact@v3
        with:
          name: Linux_arm64
          path: dist/*Linux_arm64.tar.gz
      - name: Upload assets Linux_mips64_hardfloat
        uses: actions/upload-artifact@v3
        with:
          name: Linux_mips64_hardfloat
          path: dist/*Linux_mips64_hardfloat.tar.gz
      - name: Upload assets Linux_x86_64
        uses: actions/upload-artifact@v3
        with:
          name: Linux_x86_64
          path: dist/*Linux_x86_64.tar.gz
